---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-demo
  labels:
    app: kubernetes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kubernetes-demo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
        - image: 18271959943/kubernetes-demo:0.1
          imagePullPolicy: Always
          name: kubernetes-demo
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: host
            - name: MYSQL_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: port
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql
                  key: database-name
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo
  labels:
    app: kubernetes-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30005
  selector:
    app: kubernetes-demo
