---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  username: dXNlcm5hbWU=  #username
  password: cGFzc3dvcmQ=   #password
  root-password: cm9vdA==   #root
  host: bXlzcWw=  #mysql
  port: MzMwNg==  #3306
